AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/MultilineBlockChain:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/TrailingCommaInArguments:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false